# _config.yml

# Configuración para GitHub Pages
baseurl: "/catalogos" # Nombre del repositorio en GitHub
url: "https://calzados-azaleia-peru-s-a.github.io" # URL de GitHub Pages

# Configuración de la colección de productos (si es necesario)
collections:
  products:
    output: true

# Otras configuraciones
markdown: kramdown
theme: minima
