# _config.yml

# Configuraci칩n para GitHub Pages
baseurl: "/catalogos" # Ruta base del repositorio en GitHub
url: "https://calzados-azaleia-peru-s-a.github.io/catalogos" # URL de GitHub Pages completa

# Configuraci칩n de la colecci칩n de productos
collections:
  products:
    output: true # Esto habilita la salida de las p치ginas de productos

# Otras configuraciones
markdown: kramdown
theme: minima
