# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# _config.yml

# Configuración básica para GitHub Pages
title: "Catálogo de Azaleia"
email: tu-email@ejemplo.com
description: "Catálogo interactivo de productos Azaleia"
baseurl: "/catalogos" # Nombre del repositorio en GitHub (es muy importante)
url: "https://Calzados-Azaleia-Peru-S-A.github.io" # URL de GitHub Pages

# Excluir archivos y carpetas que no queremos subir
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - _site

# Colección de productos (opcional si manejas productos como colección)
collections:
  products:
    output: true

# Configuración del tema y Markdown
markdown: kramdown
theme: minima # Cambia esto si tienes otro tema


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
