adria500blanco:
  name: ADRIA-500 BLANCO
  price: 119.9
adria500lila:
  name: ADRIA-500 LILA
  price: 119.9
adria500negro:
  name: ADRIA-500 NEGRO
  price: 119.9
adria500verde:
  name: ADRIA-500 VERDE
  price: 119.9
adria512crema:
  name: ADRIA-512 CREMA
  price: 109.9
adria512jeans:
  name: ADRIA-512 JEANS
  price: 109.9
adria512marino:
  name: ADRIA-512 MARINO
  price: 109.9
adria512negro:
  name: ADRIA-512 NEGRO
  price: 109.9
adria514beige:
  name: ADRIA-514 BEIGE
  price: 119.9
adria514lila:
  name: ADRIA-514 LILA
  price: 119.9
adria514negro:
  name: ADRIA-514 NEGRO
  price: 119.9
adria515beige:
  name: ADRIA-515 BEIGE
  price: 119.9
adria515malva:
  name: 'ADRIA-515 MALVA '
  price: 119.9
adria515negro:
  name: ADRIA-515 NEGRO
  price: 119.9
adria518beige:
  name: ADRIA-518 BEIGE
  price: 119.9
adria518marfil:
  name: ADRIA-518 MARFIL
  price: 119.9
adria518negro:
  name: ADRIA-518 NEGRO
  price: 119.9
anais263marfil:
  name: ANAIS-263 MARFIL
  price: 129.9
aura680negro:
  name: AURA-680 NEGRO
  price: 179.9
azaleiaayla048beigeclaro:
  name: AZALEIA AYLA-048 BEIGE CLARO
  price: 99.9
azaleiaayla048negro:
  name: AZALEIA AYLA-048 NEGRO
  price: 99.9
azaleiaericasoftlighttam831negro:
  name: AZALEIA ERICA SOFT LIGHT TAM-831 NEGRO
  price: 119.9
azaleiafabilightlinetam908negro:
  name: AZALEIA FABI LIGHT LINE TAM-908 NEGRO
  price: 99.9
azaleiafabilightlinetam908rose:
  name: AZALEIA FABI LIGHT LINE TAM-908 ROSE
  price: 99.9
azaleiagreicesoftpapete833hueso:
  name: AZALEIA GREICE SOFT PAPETE-833 HUESO
  price: 129.9
azaleiagreicesoftpapete833marronclaro:
  name: AZALEIA GREICE SOFT PAPETE-833 MARRON CLARO
  price: 129.9
azaleiagreicesoftpapete833negro:
  name: AZALEIA GREICE SOFT PAPETE-833 NEGRO
  price: 129.9
azaleiagreicesoftpapete833nude:
  name: AZALEIA GREICE SOFT PAPETE-833 NUDE
  price: 129.9
azaleiahannasofthighplatthong569capuccino:
  name: AZALEIA HANNA SOFT HIGH PLAT THONG-569 CAPUCCINO
  price: 129.9
azaleiahannasofthighplatthong569lila:
  name: AZALEIA HANNA SOFT HIGH PLAT THONG-569 LILA
  price: 129.9
azaleiahannasofthighplatthong569negro:
  name: AZALEIA HANNA SOFT HIGH PLAT THONG-569 NEGRO
  price: 129.9
azaleiajaque935negro:
  name: AZALEIA JAQUE-935 NEGRO
  price: 109.9
azaleiajaque935nudeoscuro:
  name: AZALEIA JAQUE-935 NUDE OSCURO
  price: 109.9
azaleiajaque935verdeclaro:
  name: AZALEIA JAQUE-935 VERDE CLARO
  price: 109.9
azaleiakatesoftduoslideplatfem549negro:
  name: AZALEIA KATE SOFT DUO SLIDE PLAT FEM-549 NEGRO
  price: 119.9
azaleiakatesoftduoslideplatfem549nude:
  name: AZALEIA KATE SOFT DUO SLIDE PLAT FEM-549 NUDE
  price: 119.9
azaleialiasoftcaretam836negro/beige:
  name: AZALEIA LIA SOFT CARE TAM-836 NEGRO/BEIGE
  price: 109.9
azaleialilianfem902marron:
  name: AZALEIA LILIAN FEM-902 MARRON
  price: 119.9
azaleialivia973cobre:
  name: AZALEIA LIVIA-973 COBRE
  price: 89.9
azaleialivia973malva:
  name: AZALEIA LIVIA-973 MALVA
  price: 89.9
azaleialivia973negro:
  name: AZALEIA LIVIA-973 NEGRO
  price: 89.9
azaleialivia973palorosa:
  name: AZALEIA LIVIA-973 PALO ROSA
  price: 89.9
azaleialorenacomfyflat868negro:
  name: AZALEIA LORENA COMFY FLAT-868 NEGRO
  price: 89.9
azaleialorenacomfyflat868nudeclaro:
  name: AZALEIA LORENA COMFY FLAT-868 NUDE CLARO
  price: 89.9
azaleialouisesofthighplatsandal568negro:
  name: AZALEIA LOUISE SOFT HIGH PLAT SANDAL-568 NEGRO
  price: 139.9
azaleialouisesofthighplatsandal568nude:
  name: AZALEIA LOUISE SOFT HIGH PLAT SANDAL-568 NUDE
  price: 139.9
azaleialouisesofthighplatsandal568palorosa:
  name: AZALEIA LOUISE SOFT HIGH PLAT SANDAL-568 PALO ROSA
  price: 139.9
azaleialouisesofthighplatsandal568verdemilitaroscuro:
  name: AZALEIA LOUISE SOFT HIGH PLAT SANDAL-568 VERDE MILITAR OSCURO
  price: 139.9
azaleiamaite045beigegliter:
  name: AZALEIA MAITE-045 BEIGE GLITER
  price: 79.9
azaleiamaite045negroglitter:
  name: AZALEIA MAITE-045 NEGRO GLITTER
  price: 79.9
azaleiamaite045rosametalizado:
  name: AZALEIA MAITE-045 ROSA METALIZADO
  price: 79.9
azaleiamaite045verde:
  name: AZALEIA MAITE-045 VERDE
  price: 79.9
azaleiamartina936azuljeans:
  name: AZALEIA MARTINA-936 AZUL JEANS
  price: 89.9
azaleiamartina936beige:
  name: AZALEIA MARTINA-936 BEIGE
  price: 89.9
azaleiamartina936negro:
  name: AZALEIA MARTINA-936 NEGRO
  price: 89.9
azaleiamayapapete970capuccino:
  name: AZALEIA MAYA PAPETE-970 CAPUCCINO
  price: 109.9
azaleiamayapapete970negro:
  name: AZALEIA MAYA PAPETE-970 NEGRO
  price: 109.9
azaleiamorganafem972negro:
  name: AZALEIA MORGANA FEM-972 NEGRO
  price: 0.0
azaleiamorganafem972nude:
  name: AZALEIA MORGANA FEM-972 NUDE
  price: 0.0
azaleiamorganafem972verde:
  name: AZALEIA MORGANA FEM-972 VERDE
  price: 0.0
azaleiasara971hueso:
  name: AZALEIA SARA-971 HUESO
  price: 89.9
azaleiasara971negro:
  name: AZALEIA SARA-971 NEGRO
  price: 89.9
azaleiasara971nude:
  name: AZALEIA SARA-971 NUDE
  price: 89.9
azaleiasofthighplatthongfem679beige:
  name: AZALEIA SOFT HIGH PLAT THONG FEM-679 BEIGE
  price: 129.9
azaleiasofthighplatthongfem679petroleo:
  name: AZALEIA SOFT HIGH PLAT THONG FEM-679 PETROLEO
  price: 129.9
azaleiaveratherapypapad451marron:
  name: AZALEIA VERA THERAPY PAP AD-451 MARRON
  price: 129.9
azaleiaveratherapypapad451negro:
  name: AZALEIA VERA THERAPY PAP AD-451 NEGRO
  price: 129.9
azaleiaveratherapypapad451nude:
  name: AZALEIA VERA THERAPY PAP AD-451 NUDE
  price: 129.9
azaleiaveratherapypapad451nudeoscuro:
  name: AZALEIA VERA THERAPY PAP AD-451 NUDE OSCURO
  price: 129.9
azanyloncamisetatermicaml602beige:
  name: AZA NYLON CAMISETA TERMICA ML-602 BEIGE
  price: 21.9
azanyloncamisetatermicaml602blanco:
  name: AZA NYLON CAMISETA TERMICA ML-602 BLANCO
  price: 21.9
azanyloncamisetatermicaml602negro:
  name: AZA NYLON CAMISETA TERMICA ML-602 NEGRO
  price: 21.9
azanylonlegging102negro:
  name: AZA NYLON LEGGING-102 NEGRO
  price: 25.9
azgelballcush123transparentevinyl:
  name: AZGEL BALL CUSH-123 TRANSPARENTE VINYL
  price: 19.9
azgelheelshield122transparentevinyl:
  name: AZGEL HEEL SHIELD-122 TRANSPARENTE VINYL
  price: 16.9
azgelslimcomf120ceniza/transparente:
  name: AZGEL SLIM COMF-120 CENIZA/TRANSPARENTE
  price: 33.9
azgelslipspotstrip121transparentevinyl:
  name: AZGEL SLIP SPOT STRIP-121 TRANSPARENTE VINYL
  price: 29.9
becca086jeans:
  name: BECCA-086 JEANS
  price: 169.9
bonnie019negro:
  name: BONNIE-019 NEGRO
  price: 249.9
bonnie019taupe:
  name: BONNIE-019 TAUPE
  price: 249.9
celia291taupe:
  name: CELIA-291 TAUPE
  price: 139.9
cremarenovadora001incoloro:
  name: CREMA RENOVADORA-001 INCOLORO
  price: 39.9
dina101natural:
  name: DINA-101 NATURAL
  price: 229.9
dina101negro:
  name: DINA-101 NEGRO
  price: 229.9
ecoprotector002incoloro:
  name: ECO PROTECTOR-002 INCOLORO
  price: 54.9
escobillaaplicadora001incoloro:
  name: ESCOBILLA APLICADORA-001 INCOLORO
  price: 11.9
escobillabrillo002incoloro:
  name: ESCOBILLA BRILLO-002 INCOLORO
  price: 16.9
escobillagamuza003incoloro:
  name: ESCOBILLA GAMUZA-003 INCOLORO
  price: 19.9
eva831bordo:
  name: EVA-831 BORDO
  price: 129.9
eva831hueso:
  name: EVA-831 HUESO
  price: 129.9
eva831negro:
  name: EVA-831 NEGRO
  price: 129.9
eva834beige:
  name: EVA-834 BEIGE
  price: 139.9
eva834bordo:
  name: EVA-834 BORDO
  price: 139.9
eva834negro:
  name: EVA-834 NEGRO
  price: 139.9
eva836marfil:
  name: EVA-836 MARFIL
  price: 129.9
eva836negro:
  name: EVA-836 NEGRO
  price: 129.9
eva836nude:
  name: EVA-836 NUDE
  price: 129.9
eva844blanco:
  name: EVA-844 BLANCO
  price: 119.9
eva844capuccino:
  name: EVA-844 CAPUCCINO
  price: 119.9
eva844negro:
  name: EVA-844 NEGRO
  price: 119.9
gaby303negro:
  name: GABY-303 NEGRO
  price: 149.9
gaby303taupe:
  name: GABY-303 TAUPE
  price: 149.9
gaby306plomo:
  name: GABY-306 PLOMO
  price: 149.9
ginny541tan:
  name: GINNY-541 TAN
  price: 149.9
ginny542dorado:
  name: GINNY-542 DORADO
  price: 149.9
ginny542ladrillo:
  name: GINNY-542 LADRILLO
  price: 149.9
i24billeteratyra511marfil:
  name: I24 BILLETERA TYRA-511 MARFIL
  price: 69.9
i24billeteratyra511marino:
  name: I24 BILLETERA TYRA-511 MARINO
  price: 69.9
i24ivonne479marfil:
  name: I24 IVONNE-479 MARFIL
  price: 139.9
i24ivonne479marino:
  name: I24 IVONNE-479 MARINO
  price: 139.9
i24jandi480tan:
  name: I24 JANDI-480 TAN
  price: 139.9
i24jandi480verde:
  name: I24 JANDI-480 VERDE
  price: 139.9
i24jisoo907negro:
  name: I24 JISOO-907 NEGRO
  price: 105.98
i24majo487dorado:
  name: I24 MAJO-487 DORADO
  price: 139.9
i24majo487hueso:
  name: I24 MAJO-487 HUESO
  price: 139.9
i24miriam469negro:
  name: I24 MIRIAM-469 NEGRO
  price: 129.9
i24miriam469whisky:
  name: I24 MIRIAM-469 WHISKY
  price: 129.9
i24perla959arena:
  name: I24 PERLA-959 ARENA
  price: 129.9
i24perla959negro:
  name: I24 PERLA-959 NEGRO
  price: 129.9
i24perla959rojo:
  name: I24 PERLA-959 ROJO
  price: 129.9
i24tilsa468negro:
  name: I24 TILSA-468 NEGRO
  price: 129.9
i24tilsa468taupe:
  name: I24 TILSA-468 TAUPE
  price: 129.9
jenny034dorado:
  name: JENNY-034 DORADO
  price: 99.9
jenny034negro:
  name: JENNY-034 NEGRO
  price: 99.9
jenny035beige:
  name: JENNY-035 BEIGE
  price: 99.9
jenny035marfil:
  name: JENNY-035 MARFIL
  price: 99.9
jodie073blanco:
  name: JODIE-073 BLANCO
  price: 179.9
kiti903beige:
  name: KITI-903 BEIGE
  price: 129.9
kiti903blanco:
  name: KITI-903 BLANCO
  price: 129.9
kiti903negro:
  name: KITI-903 NEGRO
  price: 129.9
kristin260dorado:
  name: KRISTIN-260 DORADO
  price: 129.9
kristin260hueso:
  name: KRISTIN-260 HUESO
  price: 129.9
lady282dorado:
  name: LADY-282 DORADO
  price: 119.9
lady282plata:
  name: LADY-282 PLATA
  price: 119.9
lara607calendula:
  name: LARA-607 CALENDULA
  price: 119.9
lara607negro:
  name: LARA-607 NEGRO
  price: 119.9
lara608beige/oro:
  name: LARA-608 BEIGE/ORO
  price: 129.9
lara608negroc/plata:
  name: LARA-608 NEGRO C/PLATA
  price: 129.9
lara616capuccino:
  name: LARA-616 CAPUCCINO
  price: 129.9
lara616marfil:
  name: LARA-616 MARFIL
  price: 129.9
lara616negro:
  name: LARA-616 NEGRO
  price: 129.9
lara623nude:
  name: LARA-623 NUDE
  price: 129.9
lara836jeans:
  name: LARA-836 JEANS
  price: 129.9
lara836marino:
  name: LARA-836 MARINO
  price: 129.9
lara836negro:
  name: LARA-836 NEGRO
  price: 129.9
layla132blanco/celeste:
  name: LAYLA-132 BLANCO/CELESTE
  price: 159.9
lide657canela:
  name: LIDE-657 CANELA
  price: 239.9
lide657natural:
  name: LIDE-657 NATURAL
  price: 239.9
lide657negro:
  name: LIDE-657 NEGRO
  price: 239.9
mafer305conac:
  name: MAFER-305 CONAC
  price: 249.9
mafer305negro:
  name: MAFER-305 NEGRO
  price: 249.9
mafer305taupe:
  name: MAFER-305 TAUPE
  price: 249.9
malu942capuccino:
  name: MALU-942 CAPUCCINO
  price: 129.9
malu942crema:
  name: MALU-942 CREMA
  price: 129.9
mariana797beige:
  name: MARIANA-797 BEIGE
  price: 109.9
mariana797marfil:
  name: MARIANA-797 MARFIL
  price: 109.9
mediasaza1/2caña130negro/fucsia:
  name: MEDIAS AZA 1/2 CAÑA-130 NEGRO/FUCSIA
  price: 16.9
mediasaza1/2caña130plomo/rosado:
  name: MEDIAS AZA 1/2 CAÑA-130 PLOMO/ROSADO
  price: 16.9
mediasaza3pinvcasualfem101blanco/negro/pink:
  name: MEDIAS AZA 3-P INV CASUAL FEM-101 BLANCO/NEGRO/PINK
  price: 41.9
mediasaza3pzafari553multicolores:
  name: MEDIAS AZA 3-P ZAFARI-553 MULTICOLORES
  price: 41.9
mediasazanylonbucanera303negro:
  name: MEDIAS AZA NYLON BUCANERA-303 NEGRO
  price: 12.9
mediasazanylonfalda201negro:
  name: MEDIAS AZA NYLON FALDA-201 NEGRO
  price: 9.9
mediasazanylonpantalon103beige:
  name: MEDIAS AZA NYLON PANTALON-103 BEIGE
  price: 7.9
mediasazanylonpantalon103negro:
  name: MEDIAS AZA NYLON PANTALON-103 NEGRO
  price: 7.9
mediasazanylonplantillasprotectoras301beige:
  name: MEDIAS AZA NYLON PLANTILLAS PROTECTORAS-301 BEIGE
  price: 4.9
mediasazanylonplantillasprotectoras301negro:
  name: MEDIAS AZA NYLON PLANTILLAS PROTECTORAS-301 NEGRO
  price: 4.9
mediasazanylonpushup105negro:
  name: MEDIAS AZA NYLON PUSH UP-105 NEGRO
  price: 21.9
mediasazanylontobilleras302beige:
  name: MEDIAS AZA NYLON TOBILLERAS-302 BEIGE
  price: 7.9
mediasazanylontobilleras302negro:
  name: MEDIAS AZA NYLON TOBILLERAS-302 NEGRO
  price: 7.9
mediasazatalonerasunicasualfem701pink:
  name: MEDIAS AZA TALONERAS UNI CASUAL FEM-701 PINK
  price: 14.9
mediasazatalonerasunicasualfem702negrofloral:
  name: MEDIAS AZA TALONERAS UNI CASUAL FEM-702 NEGRO FLORAL
  price: 14.9
monederoeleonora203dorado:
  name: MONEDERO ELEONORA-203 DORADO
  price: 23.9
monederoeleonora203marfil:
  name: MONEDERO ELEONORA-203 MARFIL
  price: 23.9
monederoeleonora203negro:
  name: MONEDERO ELEONORA-203 NEGRO
  price: 23.9
monederokarime310marfil:
  name: MONEDERO KARIME-310 MARFIL
  price: 25.9
neceserflori111marron:
  name: NECESER FLORI-111 MARRON
  price: 39.9
neceserflori111negro:
  name: NECESER FLORI-111 NEGRO
  price: 39.9
neceserzaira742cafe:
  name: NECESER ZAIRA-742 CAFE
  price: 39.9
neceserzaira742lila:
  name: NECESER ZAIRA-742 LILA
  price: 39.9
neceserzaira742marfil:
  name: NECESER ZAIRA-742 MARFIL
  price: 39.9
neceserzaira742negro:
  name: NECESER ZAIRA-742 NEGRO
  price: 39.9
nicole282capuccino:
  name: NICOLE-282 CAPUCCINO
  price: 129.9
nuri406beige:
  name: NURI-406 BEIGE
  price: 149.9
nuri406negro/negro:
  name: NURI-406 NEGRO/NEGRO
  price: 149.9
pandora019negro:
  name: PANDORA-019 NEGRO
  price: 189.9
pandora019oro:
  name: PANDORA-019 ORO
  price: 189.9
pandora019plata:
  name: PANDORA-019 PLATA
  price: 189.9
roselyn025negro:
  name: ROSELYN-025 NEGRO
  price: 129.9
roselyn025oro:
  name: ROSELYN-025 ORO
  price: 129.9
sabine036beige:
  name: SABINE-036 BEIGE
  price: 169.9
sabine036blanco:
  name: SABINE-036 BLANCO
  price: 169.9
sally380blanco:
  name: SALLY-380 BLANCO
  price: 169.9
sally380verde:
  name: SALLY-380 VERDE
  price: 169.9
shampooazaleia001incoloro:
  name: SHAMPOO AZALEIA-001 INCOLORO
  price: 29.9
sienna513blanco:
  name: SIENNA-513 BLANCO
  price: 139.9
sienna513negro:
  name: SIENNA-513 NEGRO
  price: 139.9
sienna514marfil:
  name: SIENNA-514 MARFIL
  price: 139.9
sienna514negro:
  name: SIENNA-514 NEGRO
  price: 139.9
thais072marronclaro:
  name: THAIS-072 MARRON CLARO
  price: 239.9
thais072negro:
  name: THAIS-072 NEGRO
  price: 239.9
triana061negro:
  name: TRIANA-061 NEGRO
  price: 159.9
triana061taupe:
  name: TRIANA-061 TAUPE
  price: 159.9
vittoria502cafe:
  name: VITTORIA-502 CAFE
  price: 239.9
zulema717cafe:
  name: ZULEMA-717 CAFE
  price: 249.9
zulema717conac:
  name: ZULEMA-717 CONAC
  price: 249.9
zulema717negro:
  name: ZULEMA-717 NEGRO
  price: 249.9
